apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: prometheus
      chart: prometheus-8.9.2
      component: alertmanager
      heritage: Tiller
      release: prometheus
    name: prometheus-alertmanager
    namespace: monitoring
    resourceVersion: "769764"
    selfLink: /api/v1/namespaces/monitoring/services/prometheus-alertmanager
  spec:
    clusterIP: 10.0.87.231
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
    selector:
      app: prometheus
      component: alertmanager
      release: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    creationTimestamp: "2019-04-10T02:51:11Z"
    labels:
      app: prometheus
      chart: prometheus-8.9.2
      component: kube-state-metrics
      heritage: Tiller
      release: prometheus
    name: prometheus-kube-state-metrics
    namespace: monitoring
    resourceVersion: "769765"
    selfLink: /api/v1/namespaces/monitoring/services/prometheus-kube-state-metrics
    uid: 7f7e48fd-5b3b-11e9-be59-bae0dc41df59
  spec:
    clusterIP: None
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: prometheus
      component: kube-state-metrics
      release: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    creationTimestamp: "2019-04-10T02:51:11Z"
    labels:
      app: prometheus
      chart: prometheus-8.9.2
      component: node-exporter
      heritage: Tiller
      release: prometheus
    name: prometheus-node-exporter
    namespace: monitoring
    resourceVersion: "769766"
    selfLink: /api/v1/namespaces/monitoring/services/prometheus-node-exporter
    uid: 7f7f9097-5b3b-11e9-be59-bae0dc41df59
  spec:
    clusterIP: None
    ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: prometheus
      component: node-exporter
      release: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/probe: pushgateway
    creationTimestamp: "2019-04-10T02:51:11Z"
    labels:
      app: prometheus
      chart: prometheus-8.9.2
      component: pushgateway
      heritage: Tiller
      release: prometheus
    name: prometheus-pushgateway
    namespace: monitoring
    resourceVersion: "769771"
    selfLink: /api/v1/namespaces/monitoring/services/prometheus-pushgateway
    uid: 7f87024a-5b3b-11e9-be59-bae0dc41df59
  spec:
    clusterIP: 10.0.207.178
    ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
    selector:
      app: prometheus
      component: pushgateway
      release: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-04-10T02:51:11Z"
    labels:
      app: prometheus
      chart: prometheus-8.9.2
      component: server
      heritage: Tiller
      release: prometheus
    name: prometheus-server
    namespace: monitoring
    resourceVersion: "769774"
    selfLink: /api/v1/namespaces/monitoring/services/prometheus-server
    uid: 7f8dbede-5b3b-11e9-be59-bae0dc41df59
  spec:
    clusterIP: 10.0.68.176
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus
      component: server
      release: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
