apiVersion: v1
kind: Service
metadata:
  namespace: voter-api
  labels:
    app: candidate
  name: candidate
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: candidate
