apiVersion: v1
kind: Service
metadata:
  namespace: voter-api
  labels:
    app: election
  name: election
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: election
