apiVersion: v1
kind: Service
metadata:
  namespace: voter-app
  labels:
    io.kompose.service: client
  name: client
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: client
