apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voter-app
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - image: garystafford/voter-client:angular-0.6.74
        name: client
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
