apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voter-api
  labels:
    app: voter
  name: voter
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        app: voter
    spec:
      containers:
      - image: kangxh/aks-voter-service
        name: voter
        ports:
        - containerPort: 8080
        
        env:
          - name: AZURE_SERVICE_BUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
              name: azure-service-bus
              key: connection-string
          
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
              name: azure-cosmosdb-voter
              key: connection-string
                
        command: ["/bin/sh"]
        args: ["-c", "java -Dspring.profiles.active=kub-aks -Djava.security.egd=file:/dev/./urandom -jar /voter/voter-service.jar"]
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
