apiVersion: v1
kind: Namespace
metadata:
  name: kube-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: kube-app
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: kangxh/helloworld
        ports:
        - containerPort: 80
          name: helloworld
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-app
  name: helloworld
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
