apiVersion: v1
kind: Secret
metadata:
  name: azure-service-bus
  namespace: kube-app
type: Opaque
data:
  connection-string: RW5kcG9pbnQ9c2I6Ly9rYW5neGhzZXJ2aWNlYnVzYWtzc2VhLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9SVo4VG8xZ1lNdFBCMjFCckhPYjE2djJDS3c5cjFRdW9FZHBKckdkQjZkMD0=
